### ISSUE TITLE
Missing frames in the middle of the drive slideshow/preview

### ISSUE THREAD

**Issue by LoganxDev** [commaai/connect#118]
~~It seems as though if the drive isn't long enough to fill up the full width of the screen with frames then there will be blank spots in the middle.~~ None of the video is playing for that section but the overlay of the lane lines is moving in the correct way for that section of the route on a frozen frame.

**Comment by adeebshihadeh** [comment]
Can you post the route? It's possible the frames are actually missing. You can check by downloading the qcamera file for that segment and playing it back with something like VLC.

**Comment by LoganxDev** [comment]
Unfortunately I lost the file reinstalling openpilot, and this was a couple weeks ago so I no longer have it in explorer either. I can probably get it to happen again and take a look then.
