### ISSUE TITLE
connect video stream freezing

### ISSUE THREAD

**Issue by sshane** [commaai/connect#129]
For a few of my recent drives over the past month connect just freezes on a specific frame and once seeking past it, nothing is shown but that frozen frame. Happens at about `f15e3c37c118e841|2021-08-03--10-11-38--19` for one example.

I was looking for a segment to report a model bug taking an exit abruptly, but downloading each video seems like the only workaround when this happens

**Comment by adeebshihadeh** [comment]
still hitting this?

**Comment by sshane** [comment]
Can't say I am
