### ISSUE TITLE
Update upsell/setup page

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/connect#133]
* looks weird on PC. hide the sidebar and center?
* looks small on PC and mobile
* update to comma three
* less ambiguous pair text

![image](https://user-images.githubusercontent.com/8762862/129415948-75bb2124-fdea-44c4-b387-41a6145f64bb.png)

**Comment by VirtuallyChris** [comment]
maybe we should detect a mobile resolution and remove the text which says 'with your phone' since they're already using their phone?
