### ISSUE TITLE
Redirect after login on mobile is sometimes stuck

### ISSUE THREAD

**Issue by pd0wm** [commaai/connect#165]
Happened multiple times on mobile already (iOS). After logging in with google it redirects through the api to connect. The api is already on connect, but the browser seems still stuck on the google login page. If I refresh I'm instantly logged in.

**Comment by adeebshihadeh** [comment]
@jwooning is this still an issue?

**Comment by jwooning** [comment]
Not really sure, haven't hit this in a while, but also didn't do anything to fix this.
