### ISSUE TITLE
Feature: Add device with serial number (no qr scan)

### ISSUE THREAD

**Issue by cgsmith** [commaai/connect#174]
Would be nice to have a screen that allows an add by serial number and not a QR code.

**Comment by pd0wm** [comment]
The QR code contains a JWT signed by the devices private key, proving physical ownership of the device. So I don't see a secure way to do this differently.

**Comment by cgsmith** [comment]
How does it prove physical ownership?

**Comment by pd0wm** [comment]
Because the private key is generated by the device itself and stored on the /persist partition. It should never leave the device. The JWT in the QR code is only valid for a short amount of time.
