### ISSUE TITLE
Allow removal of devices shared with you

### ISSUE THREAD

**Issue by zorrobyte** [commaai/connect#183]
As a moderator on discord, I sometimes ask users to add me to their useradmin so that I may remotely troubleshoot Cabana and use PlotJuggler.

The issue is that I've accumulated several accounts worth of data that I no longer want shared with me. This also clogs up my Comma Connect view. I don't want, or need access to other user's GPS location, camera uploads, etc and would like the ability to remove myself from their connect accounts/devices.

**Comment by JMPZ11** [comment]
I second this request. I have a long list of devices that have been shared with me - some of them from people who seem to have disappeared from the community. The ability to remove shared devices would be very helpful.

**Comment by incognitojam** [comment]
Just noting that this is possible from useradmin now.

**Comment by adeebshihadeh** [comment]
We can close this then. Moving all the useradmin functionality to connect is a separate issue.
