### ISSUE TITLE
nav: inconsistent search results

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/connect#186]
![image](https://user-images.githubusercontent.com/8762862/152120928-2cff30ba-4558-43d9-b76c-066a494c6b06.png)

![image](https://user-images.githubusercontent.com/8762862/152120939-be9f2281-7924-416f-b6a4-0abbc7966ac3.png)

**Comment by jwooning** [comment]
We can't really fix this, we don't do any filtering on the results from the HERE search api. And we previously found that this api gives the best results compared to others.
