### ISSUE TITLE
timeline engagement status seems wrong

### ISSUE THREAD

**Issue by sshane** [commaai/connect#200]
Here it looks like the user started braking to stop the car from creeping, but the timeline still shows it's engaged: 

![Screenshot from 2022-03-02 01-00-40](https://user-images.githubusercontent.com/25857203/156329589-e0084e2d-7acb-4a86-81c3-c40e45817473.png)

f1055ddb93ff2d3b|2022-02-28--17-15-08--9

**Comment by sshane** [comment]
I'm pretty sure it was out of sync on a route today, want an example?

**Comment by jwooning** [comment]
Oh the fix is not yet released to production, will do that today, let me know if it still an issue after tomorrow.
