### ISSUE TITLE
Replace raw files popup with a table

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/connect#277]
In the current UI, clips and raw segment file download are treated pretty equally, which is pretty confusing since most user just want a clip. At the same time, I think we can improve the raw file download experience. I propose making the file popup into a useradmin-style table with all the segments.

![image](https://user-images.githubusercontent.com/8762862/196507882-ee5f6a50-6573-4639-ada5-8fa607dc0625.png)

**Comment by criticic** [comment]
I'd like to work on this

**Comment by RossGGG** [comment]
Oops, sorry if I stepped on any toes here.  I started tinkering with this one a few days ago.  I was wondering if you could offer some clarification, though.  Did you mean replacing the Log Data download button in the Files popup menu with a modal window that provides the table?



<img src="https://github.com/commaai/connect/assets/5018716/d03f99fb-8dbf-4907-9008-f19b8a0036c5" height=200 />
