### ISSUE TITLE
clips: 360 video playback fails on mobile

### ISSUE THREAD

**Issue by incognitojam** [commaai/connect#282]
Haven't confirmed it happens on all devices, but it doesn't appear to work on Chrome on Pixel 6. Was reported in discord to not work on Chrome or Samsung Internet.

![Screenshot from 2022-10-21 10-35-34](https://user-images.githubusercontent.com/4038174/197255665-8bf2b5f6-0568-46f2-8560-5f4af1376cf5.png)

**Comment by adeebshihadeh** [comment]
Just checked, iOS works. Cool that it's reproducible in Chrome on your PC!

**Comment by incognitojam** [comment]
It seems to work if I replace the video URL with the video plugin example
https://photo-sphere-viewer.js.org/plugins/plugin-video.html

![Screenshot from 2022-10-21 10-59-04](https://user-images.githubusercontent.com/4038174/197259670-8c00ecba-ea79-4eab-9545-dd0df6d6f277.png)
