### ISSUE TITLE
remember last vehicle displayed and show on startup

### ISSUE THREAD

**Issue by gregjhogan** [commaai/connect#284]
If I open connect.comma.ai multiple times and have access to multiple vehicles, it seems random which vehicle is loaded, which is annoying.  I think it would be best to show the last vehicle you looked at (or something that at least makes it consistent).

**Comment by jyoung8607** [comment]
The "random" ordering I believe is the same as what you see in useradmin. Devices are shown in descending order of their last athena ping. And yes, it would be amazingly helpful if my two personal vehicles weren't pseudo-randomly interspersed among the (checking) 133 dongle IDs I currently have access to.

If I may propose an ordering:

1) Open directly to the last vehicle we were looking at, THEN
2) Sort the list by owned (vs readonly) devices, THEN
3) Further sort by any reasonable consistent criteria (alphabetic by device nickname, and then by dongle ID?)
