### ISSUE TITLE
memory leak in DriveMap

### ISSUE THREAD

**Issue by incognitojam** [commaai/connect#286]
![Screenshot from 2022-10-27 15-14-13](https://user-images.githubusercontent.com/4038174/198408164-ce00e7aa-89f3-4434-b1c9-aa6f8e0a7d3a.png)

**Comment by vishalkrishnads** [comment]
I'm not able to reproduce this.

**Comment by incognitojam** [comment]
Oh, I haven't seen this in a long time either
