### ISSUE TITLE
show connect version 

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/connect#352]
In the popup that comes up when clicking on the user icon?

**Comment by incognitojam** [comment]
Right now you can see the commit it was built with - there is hidden text at the bottom right of the device list, which you can read if you double click/highlight

![Screenshot from 2023-03-29 23-40-27](https://user-images.githubusercontent.com/4038174/228683793-8cd9e618-c78b-4ab8-ab11-b0d6902c4646.png)

**Comment by sshane** [comment]
close?
