### ISSUE TITLE
Uploaded clips not able to be seen

### ISSUE THREAD

**Issue by Zack1010OP** [commaai/connect#394]
After uploading my clips on Comma Connect, when i try to view my clips it just keeps showing the loading icon. It's been 2 days already. This is so frustrating, i've ALWAYS had problems with Comma's uploaded clips, only once did it work after @sshane helped escalate and fix it previously

i don't know what other information you need, but do let me know and i'm happy to provision all relevant details.

![image](https://github.com/commaai/connect/assets/110169434/6e9cec2a-f665-4852-95a3-78a1452ed61f)

**Comment by incognitojam** [comment]
- Can you share the dongle ID for the clips you are trying to view?
- What browser and operating system are you using?
- If you know how, open the browser developer console and take a screenshot

**Comment by Zack1010OP** [comment]
Dongle ID: ecb854b94fdfa4d5
Browser: Chrome (Mac) & iPhone App (iOS)
here is the screenshots showing the errors
![Screenshot 2023-07-10 at 12 05 00 AM](https://github.com/commaai/connect/assets/110169434/94b0a81e-772a-43c7-82c1-c0e8ff6e8493)

**Comment by Zack1010OP** [comment]
if it would help, could you kindly give me the instructions how to open up the "non-minified dev environment" do i can give you the "full errors and additional helpful warnings". thanks!

**Comment by incognitojam** [comment]
~~Can you click on the link `https://reactjs.org/docs/error-decoder.html...` and share the full URL with me?~~

**Comment by incognitojam** [comment]
Actually, fixed in 085506f9db315e5af2b147d8a97b81ee262daaf5. The fix will be live shortly. Thanks for the report!

**Comment by Zack1010OP** [comment]
![image](https://github.com/commaai/connect/assets/110169434/92905bd4-11c2-4982-9f9b-50db0d6367a6)

**Comment by Zack1010OP** [comment]
ok great, thanks incognitojam, much appreciated!!
