### ISSUE TITLE
missing loading indicator for devices

### ISSUE THREAD

**Issue by incognitojam** [commaai/connect#407]
Request to https://api.comma.ai/v1/me/devices/ can sometimes take a second, but the page looks as though it has frozen

**Comment by pedrosimao** [comment]
Hey, I would love to contribute to this project. I see no other guidelines than the information on the Readme file.
Would you be happy with some extra help?

**Comment by incognitojam** [comment]
@pedrosimao Basically just working on improving the reliability of connect, so feel free to help fix bugs and write new tests if you are able!
