### ISSUE TITLE
three ad: inconsistently shows

### ISSUE THREAD

**Issue by sshane** [commaai/connect#411]
Made a new account and didn't show up on mobile web app and desktop, then appeared after a minutes on mobile. Still missing on desktop, and I can't click anything

**Comment by incognitojam** [comment]
Fixed in https://github.com/commaai/connect/commit/5337249ad0ee21c5d7f3dca65163d123b74be6bb

**Comment by incognitojam** [comment]
Had to revert this as it broke opening route URLs - [added a new test](https://github.com/commaai/connect/commit/023f92545ea3affd3f92aa0d792b382e5ce66f6f) and will look into this again

**Comment by incognitojam** [comment]
Did a git bisect, it broke here: https://github.com/commaai/connect/commit/0660b0338f801a059fd3af977af388c486d2cd45. Must be some behaviour changed in React 18...

**Comment by incognitojam** [comment]
Fixed here https://github.com/commaai/connect/commit/555aebdd13b78ee30e9b0d5c198f57132996153a
