### ISSUE TITLE
paired device popup: add space between "device" and dongle id

### ISSUE THREAD

**Issue by sshane** [commaai/connect#412]
there's no separation between "successfully paired device" and the dongle id

**Comment by incognitojam** [comment]
I can't reproduce this 
![image](https://github.com/commaai/connect/assets/4038174/3f066f69-a17e-4ce8-9c13-ceb42caf3906)

**Comment by sshane** [comment]
On mobile ![Screenshot_20230726-132124](https://github.com/commaai/connect/assets/25857203/00335f21-7313-4019-a077-f5406bae4384)
