### ISSUE TITLE
timeline segments skip on certain route

### ISSUE THREAD

**Issue by sshane** [commaai/connect#424]
https://connect.comma.ai/db55e16f25039cb3/1625614679398/1625615630552

https://github.com/commaai/connect/assets/25857203/b44ae94f-2465-44e0-b3f3-0315d77ff0c3

seems to still play the video fine though

**Comment by incognitojam** [comment]
Not clear if it's related but there are lots of missing `events.json` files. Not sure why those would be missing, but I think this route is too old to be able to check logs.. 
![image](https://github.com/commaai/connect/assets/4038174/4aae3987-6d6e-44bc-81a5-02b13055f1a6)

**Comment by sshane** [comment]
oh so the timeline colors missing on old routes is not expected? I notice that a lot on old routes. I thought we might delete them somewhere

**Comment by incognitojam** [comment]
I don't know why only random segments would be missing. We might have a retention policy for these files...

**Comment by sshane** [comment]
If this isn't a connect bug, can we close @incognitojam?
