### ISSUE TITLE
Replace carousel lib with CSS

### ISSUE THREAD

**Issue by incognitojam** [commaai/connect#427]
`react-responsive-carousel` is only being used for the [device snapshot images](https://github.com/commaai/connect/blob/master/src/components/DeviceInfo/index.jsx#L376) on mobile. We can implement scrolling with snapping easily using [`scroll-snap-type`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-type) CSS property.

**Comment by aurnik** [comment]
Is there a recommended way to test this without a device and screenshots? I wrote a quick fix but still need to test: https://github.com/aurnik/connect/commit/1062d5d85518bff1123c697bda9a88c0fa889d04

**Comment by adeebshihadeh** [comment]
@aurnik I'm going to setup a real demo account for this reason. interested in working on #474 if I can send you over a token for that demo account?
