### ISSUE TITLE
Closing right upper double quote in tooltip

### ISSUE THREAD

**Issue by fleetingbytes** [commaai/connect#430]
When uploading files, the tooltip of the  shows the HTML entity code `&rdqou` instead of `”`
![rdquo](https://github.com/commaai/connect/assets/7075397/9a35caf9-01c0-4fae-933a-78bf758b3b7b)

I would be happy to open a PR for this, but I cannot find this particular string anywhere in the current code.

**Comment by incognitojam** [comment]
thanks for spotting this!
