### ISSUE TITLE
timeline does not show enaged state

### ISSUE THREAD

**Issue by fredyshox** [commaai/connect#433]
On older segment from 2021: `0982d79ebb0de295|2021-01-04--17-13-21--13`
While using replay you can see that openpilot is engaged 45 seconds in. This is not reflected in connect, which shows disengaged state throughout the full route: https://connect.comma.ai/0982d79ebb0de295/1609809984492/1609810045199

**Comment by sshane** [comment]
Looks like the timeline and thumbnails are missing

**Comment by incognitojam** [comment]
I think the `coords.json` and `events.json` generated files are deleted after a while, this could be a bug in chffr not connect if they were deleted while preserved
