### ISSUE TITLE
Proposal to create cross platform app after Apple's PWA EU ban

### ISSUE THREAD

**Issue by gabimoncha** [commaai/connect#450]
In order to comply with the new DMA requirements Apple will remove the PWA support on the EU market.
This [has been confirmed](https://techcrunch.com/2024/02/15/apple-confirms-its-breaking-iphone-web-apps-in-the-eu-on-purpose/) and will make Connect unusable on the new iOS version.

My suggestion is to create an Expo project and port most of the code to React Native. Expo is the best choice at the moment in order to add universal app support across all platforms (web, iOS, Android), while still reusing the code and onboard the entire React / React Native community.

Looking forward to hear the community's opinion so I can start setting up the project 😁

**Comment by adeebshihadeh** [comment]
Fortunately, the EU PWA ban has been reversed. For the forseeable future, connect will remain a web + PWA experience. Once we make it good, we can consider native.
