### ISSUE TITLE
New routes sometimes show at the bottom

### ISSUE THREAD

**Issue by nelsonjchen** [commaai/connect#465]
It appears that the first segments of these routes have a very different start date millis from the route metadata itself and the rest of the segments of the route.

Might be related to #451 's efforts.

**Comment by MarcoTheDingo** [comment]
+1 as well
Example route: 5130484aa8069bad/00000097--47b21ed11b

**Comment by nelsonjchen** [comment]
Curious if a PR to fixup the sorting at the drive list component will be taken until the backend or some other upstream component of the data is fixed.

**Comment by adeebshihadeh** [comment]
> Curious if a PR to fixup the sorting at the drive list component will be taken until the backend or some other upstream component of the data is fixed.

Yes, I'd merge that.

**Comment by nelsonjchen** [comment]
PR made, let me know if there are any issues.
