### ISSUE TITLE
Search returns no results

### ISSUE THREAD

**Issue by BBBmau** [commaai/connect#467]
Before when typing it would provide you with suggestions. This doesn't happen anymore and just gives no results found.

If this is a server issue then it would be worth showing some kind of message so that users know the reason. 

![image](https://github.com/commaai/connect/assets/65101411/787a0daa-ce06-4d53-91ea-0ce46b50ef5b)

**Comment by BBBmau** [comment]
Came across [this](https://stackoverflow.com/questions/66150974/here-api-autosuggest-occasionally-returns-401-unauthorized-when-proxied-through) that relates to this bug

The response is a 401 unauthorized error. im assuming that connect is on a freemium plan with them and they just hit their rate limit?

**Comment by ebellumat** [comment]
More details here: https://github.com/commaai/connect/issues/468

**Comment by BBBmau** [comment]
https://github.com/commaai/connect/commit/0216a272064c202e15a13283358d1f28543f60d6 solved the issue
