### ISSUE TITLE
401 status error in Here Maps API request 

### ISSUE THREAD

**Issue by ebellumat** [commaai/connect#468]
Search for adress is not working in Comma Connect.

Looks like the API Key from Here maps are not working properly, I tested on PC to inspect and the API keys are being not authorized, 401 error. 

![image](https://github.com/commaai/connect/assets/26942680/518b58f0-e15c-4177-8d23-535c9295cdd2)

**Comment by adeebshihadeh** [comment]
HERE cancelled our account for some reason. Fix has been deployed.
