### ISSUE TITLE
[$250 bounty] Use a real account for the demo experience

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/connect#474]
The demo experience is one route with some hardcoded API responses and "if demo" in a bunch of places.

Instead, the demo should be a real user and hit all the same code paths a normal user does.  

It'll be a better demo experience, and it should enable external contributors without a device to more effectively contribute. 

EDIT: @sshane has setup a demo account accessible with the below token. $250 bounty for refactoring the demo to use this token and hit all the normal code paths a real user would.
```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDg1ODI0NjUsIm5iZiI6MTcxNzA0NjQ2NSwiaWF0IjoxNzE3MDQ2NDY1LCJpZGVudGl0eSI6IjBkZWNkZGNmZGYyNDFhNjAifQ.g3khyJgOkNvZny6Vh579cuQj1HLLGSDeauZbfZri9jw
```

**Comment by ugtthis** [comment]
Would also be nice for the demo account to have

- Ability to do snapshots, current demo experience "take snapshot" button is disabled 
- An option or just by default, make the demo account have about 5-10 trips so that we can see how certain designs affect the trip list. Currently demo account only has 1 trip by default

**Comment by sshane** [comment]
Here is a token to access a read only demo device in connect! Just place it under `authorization` in your local storage to try it out. You may need to enter an incognito session. @adeebshihadeh may want to make this a bounty

`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDg1ODI0NjUsIm5iZiI6MTcxNzA0NjQ2NSwiaWF0IjoxNzE3MDQ2NDY1LCJpZGVudGl0eSI6IjBkZWNkZGNmZGYyNDFhNjAifQ.g3khyJgOkNvZny6Vh579cuQj1HLLGSDeauZbfZri9jw`
