### ISSUE TITLE
Update to latest `react-map-gl`

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/connect#476]
https://visgl.github.io/react-map-gl/

**Comment by 0x7B5** [comment]
This might not be as straightforward as it seems: 

"If you are using react-map-gl controls (Marker, Popup, NavigationControl etc.) with deck.gl's ContextProvider, do not upgrade to this version. The old approach no longer works with v7. We are moving the support for this use case to a new project that does not depend on mapbox." 

https://visgl.github.io/react-map-gl/docs/upgrade-guide

**Comment by adeebshihadeh** [comment]
If it helps, here's an older attempt from the previous connect maintainer: https://github.com/commaai/connect/pull/368/
