### ISSUE TITLE
Replace default time window with last N drives

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/connect#493]
connect currently only shows the last two weeks of drives by default. Switch it to show the last N drives instead (and load more once you hit the bottom). The date range should still be an input, just an optional one.

**Comment by hunxjunedo** [comment]
hey @jwooning , kindly assign this issue to me. I'd like to contribute.

**Comment by CodeWithInferno** [comment]
hey @jwooning , kindly assign this issue to me. I'd like to contribute.
