### ISSUE TITLE
shows routes for last year for all dongles

### ISSUE THREAD

**Issue by sshane** [commaai/connect#506]
seems to be changed by https://github.com/commaai/connect/commit/b64f2cdf318ebeff3dd95e9bba99afbb0104d071

previously:
 
![image](https://github.com/commaai/connect/assets/25857203/f75af992-1e4c-4be6-9420-3b455fb6855c)

now (1 year and a huge list that's laggy):

![image](https://github.com/commaai/connect/assets/25857203/5da489e1-6ff6-4d18-b1b1-4ad437bd8619)

d90d60569fa8bfe0's query takes 7-9s to load (https://api.comma.ai/v1/devices/d90d60569fa8bfe0/routes_segments?end=1718056800000&start=1686520800000)

**Comment by sarem-h** [comment]
#508

**Comment by sshane** [comment]
Closed by https://github.com/commaai/connect/pull/501
