### ISSUE TITLE
Add year to route date when not current year

### ISSUE THREAD

**Issue by sshane** [commaai/connect#507]
For old routes, you don't know what year it is.

**Comment by adeebshihadeh** [comment]
We're getting rid of this in #501

**Comment by sshane** [comment]
Still think it would be a good idea to add the year to the route, I don't see it in that PR

**Comment by sshane** [comment]
I think you meant to comment on https://github.com/commaai/connect/issues/506, this isn't related

**Comment by adeebshihadeh** [comment]
Oh, thought you meant on the time filter on top

**Comment by sshane** [comment]
No yeah, two routes will say June 10 but be a year apart
