### ISSUE TITLE
video always resumes when returning to a tab

### ISSUE THREAD

**Issue by jyoung8607** [commaai/connect#509]
With #484 video playback always resumes when returning to the connect tab, even if the user had manually paused before leaving the tab. User pauses should be tracked separately from the automated pause/resume when moving between browser tabs.

**Comment by sshane** [comment]
YouTube and most other players (and Nest?) don't pause when you leave the player running, it seems weird that ours does

**Comment by adeebshihadeh** [comment]
Let's just revert that one
