### ISSUE TITLE
connect says All logs/All files are uploaded but they are not

### ISSUE THREAD

**Issue by ZwX1616** [commaai/connect#518]
https://connect.comma.ai/a3e7d456317cb301/000002d4--62a561137b

**Comment by sshane** [comment]
@0x7B5 can you take a look at the code related to uploading files to see if there's anything obvious? It seems https://github.com/commaai/connect/pull/486 broke the upload all button. It's pretty critical that we can upload files reliably, so I'd appreciate if you tried!

Before:
![image](https://github.com/commaai/connect/assets/25857203/a35ca9c2-dec1-4af2-8e9e-17c4dfeca6ef)

After:
![image](https://github.com/commaai/connect/assets/25857203/123d22a5-696e-448a-9198-f80d597a5a3b)

**Comment by 0x7B5** [comment]
Looking into this
