### ISSUE TITLE
can't seek after exiting zoom with mouse back button

### ISSUE THREAD

**Issue by sshane** [commaai/connect#534]
from https://github.com/commaai/connect/pull/486. back button in the UI works though

https://github.com/commaai/connect/assets/25857203/3f5785b8-4f9f-40a8-b536-cbd45d7a7e0b

**Comment by 0x7B5** [comment]
This is getting caused because state.loop doesn't get updated properly when using mouse back button. Looking into it rn.

**Comment by sshane** [comment]
The history middleware used to reset it to the route zoom range, but now it doesn't execute

**Comment by 0x7B5** [comment]
That PR should fix it. As a side note, combining zoom and loop is probably not a bad idea (https://github.com/commaai/connect/pull/461).
