### ISSUE TITLE
OP enabled state on timeline not correct when using LKAS only

### ISSUE THREAD

**Issue by spektor56** [commaai/connect#97]
![image](https://user-images.githubusercontent.com/3619794/117887226-611f5980-b27e-11eb-9ab7-97ca7337e5e2.png)

I noticed a discrepancy in comma explorer when using my fork that allows LKAS without ACC.  The video shows the correct OP engaged state but the timeline appears to be using cruisestate.enabled from the car.  I'm using cruise control off with LKAS enabled only (manual gas and brakes).  Can the timeline be changed to use the actual OP engaged state like the video does?

Route: f280907e439de88d|2021-05-09--18-54-58

**Comment by adeebshihadeh** [comment]
Closing, same as #99
